[[directories]]
path="/home/danielviana/test"

[bucket]
name="testewatchfilebucket"
region="sa-east-1"

[db]
name="files"
mysqlread =  "root:1234@/encurtar_url?charset=utf8"
mysqlwrite = "root:1234@/encurtar_url?charset=utf8"

[[filters]]
type = ".OUT"
s3 = true
email= true
status = true
templateMail = "template.html"

[[filters]]
type = ".RET"
s3 = true
email= true
status = true
templateMail = "template_return.html"


[[emails]]
email=""
name=""

[[emails]]
email=""
name=""
