[[directories]]
path="/home/daniel/test"

[bucket]
name="testewatchfilebucket"
region="sa-east-1"

[db]
name="files"
mysqlread =  "root:1234@/encurtar_url?charset=utf8"
mysqlwrite = "root:1234@/encurtar_url?charset=utf8"
