[[directories]]
path="output"

[[directories]]
path="success"

[bucket]
name="logs-timpospago"
region="sa-east-1"

[db]
name="local"
mongoread =  "mongodb://localhost"
mongowrite = "mongodb://localhost"

[[filters]]
type = ".OUT"
s3 = true
email= true
status = true
templateMail = "template.html"

[[filters]]
type = ".RET"
s3 = true
email= true
status = true
templateMail = "template_return.html"
